### PR TITLE
Action Users List

### PR DESCRIPTION
**Pull request by abdullai-t**
####  Summary / Highlights
Currently, administrators do not have visibility into which users have marked actions as 'COMPLETED' or 'TODO'. The purpose of this pull request (PR) is to enhance visibility by listing all users associated with each action on the portal.

To accomplish this, an additional field named "User List" was added to the  "allActions" table, represented by the people icon. When the icon is clicked, it redirects to a page that displays the details of users and their association with the respective action. Additionally, a link is provided that, upon clicking, generates an email to the administrator containing the action's user list in CSV format.

#### Demo

https://github.com/massenergize/frontend-admin/assets/42780120/ef66286a-26dd-43e2-ba4e-65781dd58bb9

### CODE REVIEW

**Review by frimpongopoku — CHANGES_REQUESTED** [review]
Well done @abdullai-t 🤝  LGTM! 

Just PR conflicts to fix.

**Review by frimpongopoku — COMMENTED** [review]
Please test and check if deleting still works in AllActions. Cos deleting relies on the arrangement of things in "fashionData" so if you have touched anything, kindly check and see if deleting works as it should 🤔  @abdullai-t

**Comment by abdullai-t** [comment]
@frimpongopoku, delete works fine

**Comment by frimpongopoku** [comment]
> @frimpongopoku, delete works fine

You tested it?

**Comment by abdullai-t** [comment]
Yes

**Review by BradHN1 — APPROVED** [review]

**Comment by BradHN1** [comment]
A couple of small changes requested for the Action Users list:
1. The title above the list should be "Users that have recorded this action" instead of "Action Users"
2. The first columns should be "Recorded On" and "Completed On", and just list the dates, not times.
3. The date format should be YYYY-MM-DD, consistent with other pages, and be sortable.

**Comment by abdullai-t** [comment]
@BradHN1, I have addressed all the comments above. Here is an image
Screenshot 2023-06-20 at 9 39 12 AM

**Review by BradHN1 — APPROVED** [review]
LGTM

**Pull request merged**
