### PR TITLE
Keep form content temporarily before submitting

### LINKED ISSUE #769: when uploading an image specifying communities, I lose the action/event etc I was working on
**Describe the bug**
I am creating an action
at end, I click to  upload an image 
at top there is n invitation to upload it for specific communities,
when I click on that, it opens in SAME tab. I go through the motions there
but then what? 
 I have lost the action/event etc I was working on

**To Reproduce and suggestions for addressing this at the end of the video: 
basically, NOT invite to upload for a specific community, or if so, open that in a new tab (but questions about interaction with the action-creation tab)
see video: 

https://user-images.githubusercontent.com/30277868/199554186-7f405e6a-15d1-4911-9fd6-a81c2efd2475.mp4

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by frimpongopoku**
## Related ticket #769  

- [X] Now you wont lose any content if you are in the middle of **creating** action, event, team, and vendor and you visit some other page 
- [X] When the media library modal takes you to the main gallery page to upload content for specific communities, it will know  that you were in the middle of creating content and ask if you want to return after your upload is successful.

## DEMO 
https://user-images.githubusercontent.com/26961591/201588669-b8231437-f831-4152-9948-adc907f20f5f.mov

closes #769

### CODE REVIEW

**Review by Davidjwkinghorn — APPROVED** [review]
LGTM

**Comment by BradHN1** [comment]
@frimpongopoku - I've reviewed the code for this PR, and sorry to say I don't really like the approach you have taken for a few reasons, namely that it involves so many changes to all of the creation and editing methods, with a lot of duplicated code that has to be maintained, and with that comes the possibility of obscure bugs now or in the future of some field somewhere not working as it should.

Before testing it and merging it I would like to ask, would it be possible for most of the code changes to be in the component MassEnergizeForm, so that the progress can override the default data for each type of field under the right circumstances, and the higher level editing and creation methods would not need to know about the progress tracking?  Please think about if this would be possible.

Also I want to ask whether there is any interaction between tabs or windows.  You use both redux and localStorage to keep track of updates.  Do you need the localStorage, or could it be just done with redux?  Could the localstorage introduce any interaction between multiple tabs in a window which should be independent as far as this is concerned?

@Opoku-Agyemang - can you comment on this approach for keeping progress within a form?  This is trying to solve a certain problem when the media library steps forward in a tab, but I am concerned with modifying all the edit & create methods like this.

**Comment by frimpongopoku** [comment]
Hi @BradHN1, its awesome that you are also looking out for such things 💪🏾 🤣 . 
I am aware of the duplicate code you are worried about 🤣 🤣 , and funny enough, I Intentionally decided not  implement this change directly inside the form generator.

The reason is simple. I just simply always try to keep the form generator as generalized as possible. Not a lot of things are generalized in our code base, and as a result, we cannot share components in many areas, or even between platforms. So for the few things that are generalised and not hooked to a specific implementation, I like to keep them as they are. 

So when I had to implement this feature, I also had your idea that the easiest and cleanest way would be to implement things directly in the formgenerator. Which would mean we would have to connect the formgenerator to the admin portal redux store.... And that there, would have just ruined the "purity" of the formgenerator we have kept intact for all these years 🤣 🤣 . 
That is why I went with the other way of repeating implementation. (I am pretty sure I wrote it somewhere in code that the duplicates will be cleared up later? Cos I thought we needed this feature ASAP, and since duplicates have never been a deal breaker, I was like why not 🤣 ? )
I probably should have included all these in my PR descriptions. Sorry 🙏🏾 


Also 

Redux is a temporary store, when the user refreshes, everything is gone! 
That is why I keep things in local storage so that when the user refreshes, we are still able to retrieve their progress and put it back in redux.
And No, we cant skip using redux to directly to use local storage. Local storage does not have all the wirings that trigger state updates when changes happen in react.

**Comment by BradHN1** [comment]
Thanks for the explanation. Though I would prefer it is fixed in the form generator as a capability that any form existing or future can use.  It could be enabled/disabled with a parameter to the component. If need be I think you can hide the redux details in a utility routine. 

It is not necessary that the progress is retained through a browser refresh, in fact preferable that a refresh reloads the original content. So I don’t think the local storage should be needed.

**Comment by frimpongopoku** [comment]
> Thanks for the explanation. Though I would prefer it is fixed in the form generator as a capability that any form existing or future can use. It could be enabled/disabled with a parameter to the component. If need be I think you can hide the redux details in a utility routine. It is not necessary that the progress is retained through a browser refresh, in fact preferable that a refresh reloads the original content. So I don’t think the local storage should be needed.
> […](#)
> Sent from my iPhone
> On Dec 11, 2022, at 9:46 AM, Frimpong Opoku Agyemang ***@***.***> wrote: ﻿ Hi @BradHN1, its awesome that you are also looking out for such things 💪🏾 🤣 . I am aware of the duplicate code you are worried about 🤣 🤣 , and funny enough, I Intentionally decided not implement this change directly inside the form generator. The reason is simple. I just simply always try to keep the form generator as generalized as possible. Not a lot of things are generalized in our code base, and as a result, we cannot share components in many areas, or even between platforms. So for the few things that are generalised and not hooked to a specific implementation, I like to keep them as they are. So when I had to implement this feature, I also had your idea that the easiest and cleanest way would be to implement things directly in the formgenerator. Which would mean we would have to connect the formgenerator to the admin portal redux store.... And that there, would have just ruined the "purity" of the formgenerator we have kept intact for all these years 🤣 🤣 . That is why I went with the other way of repeating implementation. (I am pretty sure I wrote it somewhere in code that the duplicates will be cleared up later? Cos I thought we needed this feature ASAP, and since duplicates have never been a deal breaker, I was like why not 🤣 ? ) I probably should have included all these in my PR descriptions. Sorry 🙏🏾 Also Redux is a temporary store, when the user refreshes, everything is gone! That is why I keep things in local storage so that when the user refreshes, we are still able to retrieve their progress and put it back in redux. And No, we cant skip using redux to directly to use local storage. Local storage does not have all the wirings that trigger state updates when changes happen in react. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.

@BradHN1  

When I say I save things in local storage so that we can retrieve after refresh, I do not mean everything in redux. In fact, we do not save anything in local storage that can be retrieved from or saved in the backend. Local storage only comes in when we need to keep some content, yet, we do not want to put it in our database. Things like: the user's selected table filters per page, the user's last visited route, and in this case -- what the user has written so far, while they are trying to create content... 

Every other data is directly retrieved from the API after refresh into redux as it should. So I guess what I am trying to say is that,  we are not using local storage in place of the backend. It is a convenient way of persisting details that belong to a specific user that are either temporary, or just not  "backend-worthy".



All things aside, I do have a better way in mind that fixes all our problems, keeps the form generator as it is, and does not propagate duplicate code. Since this feature isn't in the list for our next deployment, I can implement that now.  So I guess I will close this PR, and ping everyone back when I am done here 🤝 .

**Pull request closed without merging**
