### PR TITLE
Async download frontend integration

### PR DESCRIPTION
**Pull request by abdullai-t**
https://user-images.githubusercontent.com/42780120/159575699-42ebd3fc-7474-4980-ab37-13c472fcae0c.mov

### CODE REVIEW

**Review by sopokuagyemang — APPROVED** [review]
does the user actually get an email yet? or we are yet to implement that?

**Comment by abdullai-t** [comment]
> 
The user gets the email

**Review by BradHN1 — APPROVED** [review]
LGTM

**Pull request merged**
