### PR TITLE
feat: Carbon calculator link is now complete :handshake:

### PR DESCRIPTION
**Pull request by frimpongopoku**
####  Summary / Highlights

Link on carbon calculator instructions modal is now clickable 
Screenshot 2024-05-28 at 10 51 45

#### Requirements

* [ ] I've read and understood the [Contributing Guidelines](/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [ ] I've tested my changes manually.
* [ ] I've added unit tests to my PR.

##### Transparency ([Project board](https://github.com/orgs/massenergize/projects/7/views/2))
* [X] I've given my PR a meaningful title.
* [X] I linked this PR to the relevant issue.
* [X] I moved the linked issue from the "Sprint backlog" to "In progress" when I started this.
* [ ] I moved the linked issue to "QA Verification" now that it is ready to merge.

**What kind of change does this PR introduce?** (check at least one)

- [X] Bugfix
- [X] Feature
- [ ] Performance improvement
- [ ] Feature removal
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [X] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] It's submitted to the `dev` branch or to a feature branch, _not_ the `main` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the
  issue number)
- [ ] All tests are
  passing: [Contributing Guidelines](/blob/master/.github/contributing.md#development-setup)
- [ ] New/updated tests are included

**Other information: Any otherthing we need to know**

### CODE REVIEW

**Review by archx3 — APPROVED** [review]

**Comment by BradHN1** [comment]
The document the dialog links to is obsolete.  That needs to be fixed.  I'll update it within the next week.

**Comment by archx3** [comment]
> The document the dialog links to is obsolete. That needs to be fixed. I'll update it within the next week.

@BradHN1 to be clear, is the update going to be made on the same document or a totally new document with a different link is going to be used

**Comment by BradHN1** [comment]
good point.  We could probably update it in the same google doc so the link would work.

**Comment by archx3** [comment]
> good point. We could probably update it in the same google doc so the link would work.

Creat

**Pull request merged**
