### PR TITLE
end date autofills, and dates are properly validated

### LINKED ISSUE #675: [Feature] event end date: fill in autmoatically to be same as start date
**User Story.**
As a _Cadmin
I want to avoid entering wrong dates for events / not to enter the end date for an event twice
So that I save time

**Additional details/context**
Debby in natick: When entering an Event, there is nothing to prevent the Cadmin from entering 2 dates that are not in chronological order.  See screen shot, where 2nd date is BEFORE the 1st date.  As many Events take place on a single day,  it would be great if the 2nd date could be auto-filled with the first date, with the Cadmin still having the option to change it to an even later date.

**Value added.**
What do you think the value of adding this feature is? Help managers and developers know how this should be prioritized.

**Acceptance criteria.**
The conditions that must be met for this to be done. For example, for a login feature: User is securely and reliably logged in until timeout or manual sign-out.

### PR DESCRIPTION
**Pull request by frimpongopoku**
Related ticket #675  

- [X] End date will be auto filled with start date that the admin chooses. They can then manipulate as they see fit from there... 

https://user-images.githubusercontent.com/26961591/185320208-7bd460c2-36d4-4e59-97da-99b6d8f19e4c.mov

- [X] Also dates are properly validated so that end date comes later than the start date

Uploading Screen Recording 2022-08-18 at 10.45.50.mov…

closes #675

### CODE REVIEW

**Comment by BradHN1** [comment]
@frimpongopoku - good work, this has bothered me for ages, never got around to fixing it.  A couple minor tweaks I'd like to request:
1. When you create an event, can you make the minutes not come out randomly, but set to zero.  7:00 am rather than 7:42 am.
2. Can you make the default end time come out as the start time plus one hour?  Instead of equal to the start time.

**Comment by frimpongopoku** [comment]
> @frimpongopoku - good work, this has bothered me for ages, never got around to fixing it. A couple minor tweaks I'd like to request:
> 
> 1. When you create an event, can you make the minutes not come out randomly, but set to zero.  7:00 am rather than 7:42 am.
> 2. Can you make the default end time come out as the start time plus one hour?  Instead of equal to the start time.

Makes a lot of sense 🤝  will add them.

**Comment by frimpongopoku** [comment]
@BradHN1 
- [ ] End date is now automatically set 1hr ahead 
- [ ] The default date is put on 0 mins, and 0 secs

https://user-images.githubusercontent.com/26961591/186061022-fec82b08-353e-4575-ac15-3883371de412.mov

**Review by BradHN1 — APPROVED** [review]
LGTM - thanks!

**Pull request merged**
