### PR TITLE
Better media library flow

### PR DESCRIPTION
**Pull request by frimpongopoku**
## Related ticket: https://github.com/massenergize/frontend-admin/issues/805

@kaatvds  @BradHN1 

Here are a few developments on making the media library better.  

- [X] When the media library opens, it starts with the actual upload page not the gallery, as suggested by @BradHN1 

- [X] In regards to visuals, I have made tweaks to make sure you can actually see which tab you are currently in. (i.e Uploading or choosing from the library). 
- [X] I have changed the  positions of the action buttons the let users remove/crop their selected image. It's now at the top. So, you dont have to scroll to the bottom of the modal to see those options (Check the video below to see what I mean).

### Media Library Modal Before ( i.e whats in PROD now)
https://user-images.githubusercontent.com/26961591/229997554-c614a9ac-276b-4a97-91bb-39fcd44878fb.mov

### After modifications 
Screenshot 2023-04-05 at 10 03 20

In terms of actual functionality changes, the upload flow has changed. The steps used to be: 
1. Select an image 
2. Click upload & get redirected to the next tab (i.e. list of images)
3. Then select the image you just uploaded
4. And then click "insert" 

Now: 

1. Select an image 
2. Click "Upload & Insert". Your image will be uploaded and automatically preselected.

## Here is how it works 

https://user-images.githubusercontent.com/26961591/229999958-69d3d527-b75c-45e2-9553-3e5ec063df08.mov

### CODE REVIEW

**Comment by BradHN1** [comment]
@frimpongopoku - some problems I found testing this branch.  When I click upload and insert, nothing happens.  And there are a lot of warnings in the javascript console.

**Comment by frimpongopoku** [comment]
@BradHN1  you might have to re-upload the video here 🤣

**Comment by BradHN1** [comment]
Ok - thanks

**Comment by BradHN1** [comment]
One bug observed in local testing:
I'm editing my community, which has a logo (using dev branch code):
Screenshot 2023-04-13 at 5 31 02 AM

But with this branch, the existing logo does not appear:
Screenshot 2023-04-13 at 5 31 47 AM

**Comment by frimpongopoku** [comment]
Yes @BradHN1  you will see the infinite spinner because that fix was done separately.

**Comment by frimpongopoku** [comment]
@BradHN1  Just added some commits. Ive fixed default thing not showing, the infinite loading thingy, and now its uploading. When you have time, test again and let me know if  it works on your end as well 🤝

**Pull request merged**
