### PR TITLE
Everything uses media library

### PR DESCRIPTION
**Pull request by frimpongopoku**
So while I was patiently waiting for the annual MassEnergize **deployment** festival to get my tests in 💀 🤣 🤣 , I was working on this 🌚 🤣 

This PR goes hand-in-hand with [this api PR](https://github.com/massenergize/api/pull/509)

- [X] Action creation & Edit 
- [X] Event creation & Edit 
- [X] Team creation & Edit 
- [X] Vendor creation & Edit 
- [X]  Community Homepage Edits -- Soon after cropping
- [X] Testimonial creation & Edit

Admins can 
- [X] Select any image from the library when they are creating, or editing  
- [X] Admins can load more content while in the library to stream in more images 
- [X] If the images available do not suit any admin, they can easily upload a new one by browsing, or dragging in 
- [X] Before uploading, an admin could also set if they want the image they are uploading to be available to other communities as well 

The library in the form shows all images:
- [X] Uploaded by the current admin
- [X] Images made public by admins of completely different communities
- [X] And generally all images related to any content(events, actions, teams etc) that is under any community an admin manages. 

Here is how it works ( editing an action) 

https://user-images.githubusercontent.com/26961591/169237706-5af1ce92-b210-474f-8544-386b2803d1ce.mov

_saw that tooo_ 💀 🤣  
_I added the 40char fix on the frontend side as well_

How it works when you add your own pic 

https://user-images.githubusercontent.com/26961591/169239473-5bae2956-57bf-4eae-9c72-f0cd8f684874.mov

Got blocked for a while because of a troublesome infinite re-rendering error, but wheew, I won 👯‍♂️ 👯‍♂️  🤣 🤣 . 
_(Frimpong Wins = 14,565 Admin Portal Bug Wins = 1 ) Just in case anyone is interested in the score line_ 🤣 🤣 🤣 🤣

### CODE REVIEW

**Comment by Davidjwkinghorn** [comment]
Will try to get this and the other PR that goes with this reviewed and merged tomorrow. Brad wanted to hold this till the next release.

**Review by Davidjwkinghorn — APPROVED** [review]
Looking great! I'm glad you're update the formatting of some other code too to keep it consistent.

**Comment by Davidjwkinghorn** [comment]
While I was testing this I found I can no longer access the edit community page. This does still work in the admin portal dev branch. 

https://user-images.githubusercontent.com/15150372/171926447-0b074614-3561-4561-9c23-9679b6aae205.mov

**Comment by frimpongopoku** [comment]
Great catch @Davidjwkinghorn. Its fixed now!

**Review by Davidjwkinghorn — APPROVED** [review]
Looking good! I defiantly like the look of the media library.

**Pull request merged**
