### PR TITLE
New media library updates - Please Read

### PR DESCRIPTION
**Pull request by frimpongopoku**
###  ⚠️ No new libraries used. So there should no need for "npm install" 

Following @kaatvds 's [doc](https://docs.google.com/document/d/15W2CmURenZjPxKq71nCuw2gP-nljN3Q7hWhQj1EEdzs/edit?usp=sharing), I have implemented some of the high priority requests described... 

### This PR contains the following features:  

- [X] The media library now requires a user to fill a form before they are able to upload their image. 
- [X] The form asks for (copyright information, depiction of individuals underage, descriptive words etc.. as requested 
- [X] The information collected are shown on the sidebar every time you click an image in the media library 
- [X] The sidebar also now shows Image usage information. (i.e. if an image is being used in an action,event,vendors etc) 
- [X] Library now has newly designed filters. With options as requested in the doc ( recent uploads, mine, by keyword, from other admins, by community...)  
- [X] Editing: After an admin uploads an image and adds some information about the upload, they are able to make changes anytime as they see fit. All through the modal 
- [X] Deleting : Now admins can delete their image right through the modal 

###  UP NEXT
The following are not implemented here, but are soon to come 
- Including our Media Library into  TinyMCE editor  
- Setting up pre-defined aspect ratios for users when cropping 
- Cropping already uploaded images 
- Functionality to automatically identify duplicate images and remove

# DEMOS 

### New upload flow 

https://github.com/massenergize/frontend-admin/assets/26961591/04dc46ec-629b-4425-bcae-d29e5d7ca1c9

### View image details 

https://github.com/massenergize/frontend-admin/assets/26961591/4c2e5156-c417-46f9-a685-9118ccec1f4a

### Edit image details 

https://github.com/massenergize/frontend-admin/assets/26961591/f3d28a4d-2d1e-44df-a74b-fa828eefabea

### Filtering images 
https://github.com/massenergize/frontend-admin/assets/26961591/f751ad74-4d0a-44bd-b5eb-72900f7e3b02

https://github.com/massenergize/frontend-admin/assets/26961591/757ea2e6-e712-4a7c-afe1-ee1972fd5629

### Deleting 

https://github.com/massenergize/frontend-admin/assets/26961591/27426b14-7465-4edf-9aa0-86e36cf9ab30

### CODE REVIEW

**Comment by frimpongopoku** [comment]
I had to rebase this branch and fix a lot of merge conflicts. While I was merging the conflicts, I saw that some of your features had been checked in. I did my best to track down your changes and add them but I am not entirely sure. So @abdullai-t  step into this branch and see if the work you did on "email template" is still intact 🤣 🤣 🤣 🤣  (dont commit, just test locally)

**Comment by abdullai-t** [comment]
> I had to rebase this branch and fix a lot of merge conflicts. While I was merging the conflicts, I saw that some of your features had been checked in. I did my best to track down your changes and add them but I am not entirely sure. So @abdullai-t step into this branch and see if the work you did on "email template" is still intact 🤣 🤣 🤣 🤣 (dont commit, just test locally)

We are no longer using the admin portal to manage email templates so we are good

**Comment by BradHN1** [comment]
There are incompatibilities with the node and npm version I currently use, relating to "digtal envelope routines".  What versions of those do you have?

**Comment by frimpongopoku** [comment]
> There are incompatibilities with the node and npm version I currently use, relating to "digtal envelope routines"


My Node: v14.19.2 
My NPM : 6.14.17

**Comment by kaatvds** [comment]
Kaat’s Feedback on Frmipong’s work 8/25/2023 (also [here](https://docs.google.com/document/d/15W2CmURenZjPxKq71nCuw2gP-nljN3Q7hWhQj1EEdzs/edit#bookmark=id.i7aggrxb6olo) in this doc)

**In first video: request info when uploading image.**
The instruction is: 

Screenshot 2023-08-25 at 1 53 00 PM

This seems to imply that if they don’t have permission, click “no” they can still upload as long as they attribute it. That’s is not correct. If they don’t have permission they are NOT allowed to upload it, as per [this](https://docs.google.com/document/d/15W2CmURenZjPxKq71nCuw2gP-nljN3Q7hWhQj1EEdzs/edit#bookmark=id.8vpowyhnbifn).

CHANGE TO:

Copyright

Do you have permission to use the selected item - written permission from the person whose it is, or is the image under a copyright license that allows it to be used in this circumstance)? As per the Admin MOU (LINK) you are required to have permission before uploading other people’s content. Please tick this box that you do.

O Yes   O No 

If this image needs to be attributed, please type in the name of the owner of the copyright.

**Video: image details**

Missing, please add:
name of uploading community
Not shown in videos, but when it is used by a community for an event, will it mention that when you scroll down in info sidebar?
date of upload

**video: edit image details**

QUESTION: What happens if the uploader edits a detail that affects the image on other community’s sites? E.g. which community can use it: If Enway already used it and now you deselect Enway, does the image simply disappear off the Enway site? That would be an issue.


**Video: Filtering images** 

I assume that if I want to see all images I just stay on the default (recent) and click on “Load more below”?

Filters: you could change text to: “use the option below to filter images according to who uploaded”:
“Mine” is ambiguous. Change to + add:
My community (ADD this)
I uploaded
By admins
By community
“By admins” and “by community” should show only images shared with my community, of course. 
When on “by community” it should show all communities (that have shared images)

**Video: Deleting**
Same QUESTION: What happens if the uploader deletes image already used by other admin/community? That would be an issue.

**Comment by frimpongopoku** [comment]
@kaatvds  

- [X] I have changed the filter options 

Screenshot 2023-08-28 at 10 39 06

- [X] The sidebar will also now show date and list of communities 

https://github.com/massenergize/frontend-admin/assets/26961591/bdff3c6e-a0a2-4ff8-bfc6-fade8bcc4480



1. And Yes,  the "Most Recent" which is now changed to "My Community" will show images related to any of the communities you manage sorted by the most recent. 
2. Yes, "By Admins" only shows a combined list of admins in your community(ies... if you manage multiple as a cadmin).
Screenshot 2023-08-28 at 10 54 34
3. As a Cadmin "By Community" will only show you a list of the communities you manage. Which in turn forces you to only see only images that have been shared with any of the communities you manage.

Screenshot 2023-08-28 at 10 56 12


### What happens if an admin unshares an image with a community and its already being used somewhere? 

Currently, nothing! The image still stays in place, the image will just not show up in the Gallery any longer to be used by any admin from the "removed community".  We could automatically notify the admins of the community when this happens though, what do you think?  We could notify them that "Your community no longer has access to the image that is being used  this ...action. and this... event. Please replace them" Then we could forcefully remove



### What happens when an admin deletes an image 

That will completely yank it off wherever it's being used. Again, we could notify admins who are in charge to take action 🤔 ...

**Review by BradHN1 — APPROVED** [review]
LGTM - test in dev

**Pull request merged**
