### PR TITLE
More font dialog tweaks

### PR DESCRIPTION
**Pull request by frimpongopoku**
The font dialog now shows the name of icons
Here: 
Screenshot 2022-05-10 at 10 32 30

### CODE REVIEW

**Review by abdullai-t — APPROVED** [review]
✅

**Comment by BradHN1** [comment]
@frimpongopoku - good progress, but I would like to see the following changes which were in the issue ticket before updating the admin experience:

Commonly used icons at the top  - I am making a list of the currently used icons and will order them by frequency.  Will get that to you shortly

Make icons 2x larger so we can see them better, and text larger to be able to read it

Rather than the current pagination, show icon + names, can be in multiple columns as fits on page - I would like the icons to be in column, with text next to the icon, or underneath, but all text showing.  Not ... which isn't readable

Pagination - broken into many fewer pages? - Not so important, but can avoid the pagination altogether if we have the search feature

Add a search by name -

**Comment by BradHN1** [comment]
One more request - on the page with the icon picker, underneath "Pick an icon", please show the name of the icon next to the icon.

**Review by BradHN1 — CHANGES_REQUESTED** [review]
Requests listed

**Comment by frimpongopoku** [comment]
Searching already works.

And also based on the requests, does it mean I should increase the size of
the dialog? Otherwise we probably would have 3 or 4 icons showing until
users have to scroll 🤔 thats not good experience imo.

**Comment by BradHN1** [comment]
Regarding the number of icons showing on the screen, assuming working on a laptop, if you do the Icon  + name side by side, and open the dialog at the top of the screen, you should be able to show perhaps 10 lines at a time.  If you want to use multiple columns you could get more icons showing on the screen.  

The big improvement in user experience will be having the common icons at the top, and being able to search.
Here are the 10 commonly used icons today which should come at the top (maybe with text "Commonly used icons", with a divider '-----------' after the last one.  Does this make sense::

fa fa-leaf
fa fa-calendar
fa fa-quote-left
fa fa-map-pin
fa fa-exclamation
fas fa-asterisk
fa fa-home
fa fa-book
fa fa-sun
fa fa-events

**Comment by BradHN1** [comment]
I didn't notice the search feature.  Can we make it more prominent, with "Search for icon by name:"

**Comment by frimpongopoku** [comment]
We can increase how many icons should show per page, but I don't recommend removing pagination entirely. Its also for performance. We cant just show 1000 + icons on the fly like that 😅😅. It will make everything lag. And it will get worse as the icon set grows.

**Comment by frimpongopoku** [comment]
@BradHN1 
- [X] I have increased the size of the icons 
- [X] Full names without ellipses
- [X] Names so side by side with icons
- [X] Increased number of icons per page from 50 to 200 
- [X] Now showing icons in two columns 
- [X] Added the most commonly used icons. (But right now it has no backend functionality, its just a hardcoded list showing the icons on the list you gave)

This is what it looks like now. What do you think? 🤔  
Screenshot 2022-05-11 at 13 21 48

**Comment by BradHN1** [comment]
Really good!  I think this is just what we need.

**Review by BradHN1 — APPROVED** [review]
LGTM

**Pull request merged**
