### PR TITLE
MOU PDF Page Break

### PR DESCRIPTION
**Pull request by abdullai-t**
####  Summary / Highlights
Related [Issue](https://github.com/massenergize/frontend-admin/issues/971)
The previous package we used to generate pdf from a react component had a limitation on when to break to next page as shown below.
shown

### What I added
I added two new packages 
- `react-pdf-html` to format our richtext to html fo pdf render
- `@react-pdf/renderer` converts jsx to pdf

### New PDF Look
[Memorandum of Understanding (MOU) - MassEnergize (83).pdf](https://github.com/massenergize/frontend-admin/files/11722740/Memorandum.of.Understanding.MOU.-.MassEnergize.83.pdf)

### CODE REVIEW

**Review by frimpongopoku — CHANGES_REQUESTED** [review]
Page breaks is MUCH better than the previous package, but the padding here is also WAAAY OFF 🤣 🤣

**Comment by BradHN1** [comment]
@abdullai-t - I appreciate the amount of work you've put into this, and I'm sure it can be made to work though it doesn't look proper yet (odd control characters and paragraph spacing that doesn't look right.  Actually it should fit on one side of one page, so I've changed the MOU document in Dev, Canary and Prod to use 18 point font on the title and 10 point font on the text.  Now that fits on one side of a page which is good for now with the existing code.

**Comment by abdullai-t** [comment]
MOU document is now generated at the API and emailed to the user.

**Comment by BradHN1** [comment]
LGTM

**Pull request merged**
